# Base image
FROM python:3.11-slim

# Set working directory in container
WORKDIR /app

# Copy requirements.txt first
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire repo into container
COPY . .

# Expose Cloud Run port
EXPOSE 8080

# Run the app from subfolder
CMD ["python", "gen-ai-midterm/app.py"]